### ISSUE TITLE
How to contribute to a django app?

### ISSUE THREAD

**Issue by tylerecouture** [mixkorshun/django-safe-filefield#3]
Hi!   I'd like to add a filesize limit option to this app, but I'm not sure how to setup a dev environment specifically for the app.  I've worked with Django for a few years, so I'm comfortable with my own apps within my project, but I can't seem to find any tutorials on how to contribute to discrete apps like this one.   For example, once I fork the project and clone... how do I setup django to work with the app by itself? 

Help with this would be bonus, but not expected.  Thanks a ton for the app!

**Comment by mixkorshun** [comment]
Hi! In development environment to work  with discrete apps (and any other packages) you can use pip editable installation mode: `pip install -e <package_path>`. You can read more about it here: https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs

And also you always can use unit / functional tests in discrete app. :)
